name       : data-default-instances-dlist
version    : 0.0.1
release    : 1
source     :
    - https://hackage.haskell.org/package/data-default-instances-dlist-0.0.1/data-default-instances-dlist-0.0.1.tar.gz : 7d683711cbf08abd7adcd5ac2be825381308d220397315a5570fe61b719b5959
license    : BSD-3-Clause
component  : programming.haskell
summary    : Default instances for types in dlist
description: |
    Default instances for types in dlist
builddeps  :
    - haskell-cabal-install
    - haskell-data-default-class
    - haskell-dlist
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
